# Generated by Django 5.2.17 on 2026-09-14 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_label', models.CharField(max_length=240)),
                ('appointment_at', models.DateTimeField()),
                ('problem', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('in_progress', 'กำลังซ่อม'), ('completed', 'เสร็จแล้ว'), ('cancelled', 'ยกเลิกแล้ว')], default='pending', max_length=20)),
                ('repair_notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_jobs', to=settings.AUTH_USER_MODEL)),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='garage.motorcycle')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอรับงาน'), ('accepted', 'รับงานแล้ว'), ('in_progress', 'กำลังซ่อม'), ('completed', 'เสร็จแล้ว'), ('cancelled', 'ยกเลิกแล้ว')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='garage.booking')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'in_progress'])), fields=('motorcycle',), name='one_active_booking_per_motorcycle'),
        ),
    ]
