# Generated by Django 5.2.17 on 2026-09-15 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_booking_bookingevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='shop_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('accepting_bookings', models.BooleanField(default=True)),
                ('mechanics', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'mechanics'}, related_name='service_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='garage.shop'),
        ),
    ]
