# Generated by Django 5.2.17 on 2026-09-26 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_shopconversation_shopmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=1000)),
                ('locator', models.CharField(blank=True, help_text='รุ่น/ปี/เลขหน้าหรือหัวข้อ', max_length=120)),
                ('keywords', models.JSONField(default=list, help_text='คำค้นภาษาไทย/ชื่อรุ่น เช่น ["สตาร์ท", "แบตเตอรี่"]')),
                ('content', models.TextField(max_length=1800)),
                ('is_active', models.BooleanField(default=False, help_text='เปิดหลังตรวจความถูกต้องและสิทธิ์ใช้ข้อมูล')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='บทสนทนาใหม่', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4)),
                ('message', models.TextField(max_length=1000)),
                ('reply', models.TextField(blank=True, max_length=6000)),
                ('status', models.CharField(choices=[('pending', 'กำลังตอบ'), ('completed', 'สำเร็จ'), ('failed', 'ไม่สำเร็จ')], default='pending', max_length=12)),
                ('sources', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='garage.aiconversation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'request_id'), name='ai_request_unique'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('conversation',), name='ai_one_pending_turn')],
            },
        ),
    ]
