# Generated by Django 5.2.17 on 2026-09-29 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmessage',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='shopmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sender', 'request_id'), name='shop_message_request_unique'),
        ),
    ]
