# Generated by Django 5.2.17 on 2026-10-03 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_message_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiEmbeddingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('key_hint', models.CharField(max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=160)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('section', models.CharField(max_length=120)),
                ('content', models.TextField(max_length=1800)),
                ('source_url', models.URLField(max_length=1000)),
                ('reviewed', models.BooleanField(default=False)),
                ('embedding_status', models.CharField(default='pending', max_length=20)),
                ('embedded_hash', models.CharField(blank=True, max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
