# Generated by Django 5.2.17 on 2026-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_adminauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='moderation_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='shop',
            name='moderation_status',
            field=models.CharField(choices=[('active', 'ปกติ'), ('suspended', 'ระงับชั่วคราว'), ('banned', 'แบนถาวร'), ('deleted', 'ลบถาวรจากแอป')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='shop',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
