# Generated by Django 5.2.17 on 2026-10-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0014_shop_deleted_at_shop_moderation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archive_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
