# Generated by Django 5.2.17 on 2026-10-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0015_booking_archive_reason_booking_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='archive_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='archive_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopconversation',
            name='archive_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='shopconversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopmessage',
            name='redacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopmessage',
            name='redaction_reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
