# Generated by Django 5.2.17 on 2026-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0017_motorcycleknowledge_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=12)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField()),
                ('sections', models.JSONField(default=list)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
