const { chromium } = require('playwright');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.join(__dirname, '..');
let browser, stage = 'login password layout';
(async () => {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 430, height: 932 } });
  page.setDefaultTimeout(30000);
  await page.goto('http://localhost:8000/accounts/login/');
  const password = page.locator('#id_password');
  const toggle = page.locator('button[aria-controls=id_password]');
  await toggle.waitFor();
  const inputBox = await password.boundingBox();
  const buttonBox = await toggle.boundingBox();
  assert.ok(buttonBox.x >= inputBox.x && buttonBox.x + buttonBox.width <= inputBox.x + inputBox.width);
  assert.ok(buttonBox.y >= inputBox.y && buttonBox.y + buttonBox.height <= inputBox.y + inputBox.height);
  await toggle.click();
  assert.equal(await password.getAttribute('type'), 'text');
  await toggle.click();
  await page.screenshot({ path: path.join(root, 'docs/screenshots/password-inline-mobile.png'), fullPage: true });
  stage = 'photo placement and live reverse address';
  await page.getByRole('link', { name: 'สมัครสมาชิกใหม่' }).click();
  await page.locator('[name=account_type]').selectOption('mechanic');
  assert.equal(await page.locator('[name=latitude]').getAttribute('type'), 'hidden');
  assert.equal(await page.locator('[name=longitude]').isVisible(), false);
  await page.locator('[name=shop_photo]').setInputFiles(path.join(root, 'docs/screenshots/login.png'));
  const preview = page.locator('#shop-photo-preview');
  await preview.waitFor();
  const photoBox = await preview.boundingBox();
  const uploadBox = await page.locator('[name=shop_photo]').boundingBox();
  const mapBox = await page.locator('#shop-map').boundingBox();
  assert.ok(photoBox.y > uploadBox.y && photoBox.y + photoBox.height < mapBox.y);
  await page.waitForFunction(() => Array.from(document.querySelectorAll('.leaflet-tile')).some(img => img.complete && img.naturalWidth > 0));
  const lookup = page.waitForResponse(r => r.url().includes('/accounts/shop-address/'));
  await page.locator('#shop-map').click({ position: { x: 150, y: 130 } });
  const result = await lookup;
  assert.equal(result.status(), 200);
  const data = await result.json();
  assert.ok(data.address);
  await page.getByText('เติมที่อยู่จากหมุดแล้ว', { exact: false }).waitFor();
  const address = page.locator('[name=shop_address]');
  assert.equal(await address.inputValue(), data.address);
  await page.screenshot({ path: path.join(root, 'docs/screenshots/provider-registration-autofill.png'), fullPage: true });
  console.log('PASS: inline password toggle, hidden coordinates, adjacent photo preview and live address autofill');
  stage = 'manual edits protected from delayed responses';
  await page.route('**/accounts/shop-geocode/', route => route.fulfill({ status: 404, contentType: 'application/json', body: JSON.stringify({error:'ไม่พบพิกัดสำหรับที่อยู่นี้'}) }));
  let delayed;
  let reached;
  const requested = new Promise(resolve => { reached = resolve; });
  await page.route('**/accounts/shop-address/', async route => {
    reached();
    await new Promise(resolve => { delayed = resolve; });
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({address:'Late automatic address'}) });
  });
  await page.locator('#address-from-pin').click();
  await requested;
  await address.fill('เลขที่ 99 ที่อยู่ที่ผู้ใช้แก้ไขเอง');
  delayed();
  await page.getByText('ไม่พบพิกัดสำหรับที่อยู่นี้', { exact: false }).waitFor();
  assert.equal(await address.inputValue(), 'เลขที่ 99 ที่อยู่ที่ผู้ใช้แก้ไขเอง');
  await page.unroute('**/accounts/shop-address/');
  stage = 'lookup failure preserves address and pin';
  const lat = await page.locator('[name=latitude]').inputValue();
  await page.route('**/accounts/shop-address/', route => route.fulfill({ status: 502, contentType:'application/json',
    body: JSON.stringify({error:'ค้นหาที่อยู่ไม่สำเร็จ กรุณากรอกที่อยู่เองหรือลองใหม่'}) }));
  await page.locator('#address-from-pin').click();
  await page.getByText('ค้นหาที่อยู่ไม่สำเร็จ', {exact:false}).waitFor();
  assert.equal(await address.inputValue(), 'เลขที่ 99 ที่อยู่ที่ผู้ใช้แก้ไขเอง');
  assert.equal(await page.locator('[name=latitude]').inputValue(), lat);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  console.log('PASS: delayed/error responses preserve manual address edits and selected pin');
  stage = 'live forward geocoding';
  await page.unroute('**/accounts/shop-geocode/');
  const forward = page.waitForResponse(r => r.url().includes('/accounts/shop-geocode/') && r.status() !== 429);
  await address.fill('Bangkok Thailand');
  const forwardResponse = await forward;
  assert.equal(forwardResponse.status(), 200);
  const coordinates = await forwardResponse.json();
  await page.getByText('ปักหมุดจากที่อยู่แล้ว', {exact:false}).waitFor();
  assert.equal(await address.inputValue(), 'Bangkok Thailand');
  assert.equal(Number(await page.locator('[name=latitude]').inputValue()), Number(coordinates.latitude));
  console.log('PASS: live address search positions pin without replacing typed address');
  stage = 'rate limit retry and stale forward response';
  let calls = 0;
  await page.route('**/accounts/shop-geocode/', route => {
    calls++;
    return route.fulfill({status: calls === 1 ? 429 : 200, contentType:'application/json',
      body: JSON.stringify(calls === 1 ? {error:'wait'} : {latitude:'14.123456',longitude:'100.123456'})});
  });
  await address.fill('Retry test address');
  await page.getByText('ปักหมุดจากที่อยู่แล้ว', {exact:false}).waitFor();
  assert.equal(calls, 2);
  assert.equal(await page.locator('[name=latitude]').inputValue(), '14.123456');
  await page.unroute('**/accounts/shop-geocode/');
  let releaseForward, forwardReached;
  const forwardRequested = new Promise(resolve => { forwardReached = resolve; });
  const completedForward = new Promise(resolve => {
    page.route('**/accounts/shop-geocode/', async route => {
      forwardReached();
      await new Promise(release => { releaseForward = release; });
      await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({latitude:1,longitude:2})});
      resolve();
    });
  });
  await address.fill('Delayed forward address');
  await forwardRequested;
  await page.unroute('**/accounts/shop-address/');
  await page.route('**/accounts/shop-address/', route => route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({address:'Address at latest pin'})}));
  await page.locator('#shop-map').click({position:{x:180,y:140}});
  const latestPin = await page.locator('[name=latitude]').inputValue();
  releaseForward();
  await completedForward;
  await page.getByText('เติมที่อยู่จากหมุดแล้ว', {exact:false}).waitFor();
  assert.equal(await page.locator('[name=latitude]').inputValue(), latestPin);
  assert.equal(await address.inputValue(), 'Address at latest pin');
  console.log('PASS: automatic retry, map click supersedes pending address search and updates edited address');
})().catch(error => {
  console.error(`FAIL at ${stage}: ${String(error.message).replace(/https?:\/\/\S+/g,'[url]')}`);
  process.exitCode = 1;
}).finally(async () => { if (browser) await browser.close(); });
